image: rustdocker/rust:nightly

cache:
  paths:
    - target/

pages:
  stage: deploy
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo install cargo-web
    - cargo web deploy --target=wasm32-unknown-unknown
    - mkdir public
    - mv target/deploy public
  artifacts:
    paths:
      - public
  only:
    - master
