image: rustdocker/rust:nightly

cache:
  paths:
    - target/
    - ~/.cargo

pages:
  stage: deploy
  script:
    - rustup target add wasm32-unknown-unknown
    - ./ci-install.sh
    - cargo web build --target=wasm32-unknown-unknown
    - cargo web deploy --target=wasm32-unknown-unknown
    - mkdir public
    - ls -la target/deploy
    - mv target/deploy public
  artifacts:
    paths:
      - public
  only:
    - master
