image: rustdocker/rust:nightly

cache:
  paths:
    - target/

pages:
  stage: deploy
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo install cargo-web
    - cargo build
    - cargo web deploy --target=wasm32-unknown-unknown
  artifacts:
    paths:
      - target/deploy
  only:
    - master
