language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx

rust:
  - nightly

script:
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-update
  - cargo install-update cargo-web
  - cargo install-update cargo-update
  - cargo web build --target=wasm32-unknown-unknown
  - cargo web deploy --target=wasm32-unknown-unknown

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        git clone http://github.com/davisp/ghp-import &&
        echo "calc.cgm616.me" > target/deploy/CNAME
        ./ghp-import/ghp_import.py -n -p -f -m "Site upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/deploy &&
        echo "Uploaded site to ghpages"
      fi
