language: rust
cache: cargo
dist: trusty
os: 
  - linux
  - osx

rust:
  - nightly

script:
  - rustup target add wasm32-unknown-unknown
  - ./ci-install.sh
  - cargo web build --target=wasm32-unknown-unknown
  - cargo web deploy --target=wasm32-unknown-unknown

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        git clone http://github.com/davisp/ghp-import &&
        ./ghp-import/ghp_import.py -n -p -f -m "Site upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/deploy &&
        echo "Uploaded site to ghpages"
      fi
